# mypy: ignore-errors
# isort: skip_file
# fmt: off

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: courses.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcourses.proto\"\xbb\x01\n\nRawCourses\x12\x11\n\tcourse_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ourse_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07\x63redits\x18\x04 \x01(\t\x12\x16\n\x0e\x64uration_weeks\x18\x05 \x01(\x01\x12\x1a\n\x12required_materials\x18\x06 \x03(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\x12\x17\n\x0f\x63ourse_metadata\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'courses_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RAWCOURSES']._serialized_start=18
  _globals['_RAWCOURSES']._serialized_end=205
# @@protoc_insertion_point(module_scope)
