# mypy: ignore-errors
# isort: skip_file
# fmt: off

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enrollments.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65nrollments.proto\"\xef\x01\n\x0eRawEnrollments\x12\x15\n\renrollment_id\x18\x01 \x01(\t\x12\x12\n\nstudent_id\x18\x02 \x01(\x03\x12\x10\n\x08\x63lass_id\x18\x03 \x01(\t\x12\x17\n\x0f\x65nrollment_date\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x30\n\x0b\x66\x65\x65_payment\x18\x06 \x03(\x0b\x32\x1b.RawEnrollments.Fee_payment\x1a\x45\n\x0b\x46\x65\x65_payment\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\x12\x14\n\x0cpayment_date\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enrollments_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RAWENROLLMENTS']._serialized_start=22
  _globals['_RAWENROLLMENTS']._serialized_end=261
  _globals['_RAWENROLLMENTS_FEE_PAYMENT']._serialized_start=192
  _globals['_RAWENROLLMENTS_FEE_PAYMENT']._serialized_end=261
# @@protoc_insertion_point(module_scope)
