# mypy: ignore-errors
# isort: skip_file
# fmt: off

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enrollments.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enrollments.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x65nrollments.proto\"\xef\x01\n\x0eRawEnrollments\x12\x15\n\renrollment_id\x18\x01 \x01(\t\x12\x12\n\nstudent_id\x18\x02 \x01(\x03\x12\x10\n\x08\x63lass_id\x18\x03 \x01(\t\x12\x17\n\x0f\x65nrollment_date\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x30\n\x0b\x66\x65\x65_payment\x18\x06 \x03(\x0b\x32\x1b.RawEnrollments.Fee_payment\x1a\x45\n\x0b\x46\x65\x65_payment\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\x12\x14\n\x0cpayment_date\x18\x03 \x01(\x03\x62\x06proto3'
)




_RAWENROLLMENTS_FEE_PAYMENT = _descriptor.Descriptor(
  name='Fee_payment',
  full_name='RawEnrollments.Fee_payment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='RawEnrollments.Fee_payment.amount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currency', full_name='RawEnrollments.Fee_payment.currency', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payment_date', full_name='RawEnrollments.Fee_payment.payment_date', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=261,
)

_RAWENROLLMENTS = _descriptor.Descriptor(
  name='RawEnrollments',
  full_name='RawEnrollments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enrollment_id', full_name='RawEnrollments.enrollment_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='student_id', full_name='RawEnrollments.student_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class_id', full_name='RawEnrollments.class_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enrollment_date', full_name='RawEnrollments.enrollment_date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='RawEnrollments.status', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fee_payment', full_name='RawEnrollments.fee_payment', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RAWENROLLMENTS_FEE_PAYMENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=261,
)

_RAWENROLLMENTS_FEE_PAYMENT.containing_type = _RAWENROLLMENTS
_RAWENROLLMENTS.fields_by_name['fee_payment'].message_type = _RAWENROLLMENTS_FEE_PAYMENT
DESCRIPTOR.message_types_by_name['RawEnrollments'] = _RAWENROLLMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RawEnrollments = _reflection.GeneratedProtocolMessageType('RawEnrollments', (_message.Message,), {

  'Fee_payment' : _reflection.GeneratedProtocolMessageType('Fee_payment', (_message.Message,), {
    'DESCRIPTOR' : _RAWENROLLMENTS_FEE_PAYMENT,
    '__module__' : 'enrollments_pb2'
    # @@protoc_insertion_point(class_scope:RawEnrollments.Fee_payment)
    })
  ,
  'DESCRIPTOR' : _RAWENROLLMENTS,
  '__module__' : 'enrollments_pb2'
  # @@protoc_insertion_point(class_scope:RawEnrollments)
  })
_sym_db.RegisterMessage(RawEnrollments)
_sym_db.RegisterMessage(RawEnrollments.Fee_payment)


# @@protoc_insertion_point(module_scope)
