# mypy: ignore-errors
# isort: skip_file
# fmt: off

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instructors.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='instructors.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11instructors.proto\"\xfa\x01\n\x0eRawInstructors\x12\x15\n\rinstructor_id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x11\n\thire_date\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x17\n\x0fsubjects_taught\x18\x06 \x03(\t\x12\x38\n\x0foffice_location\x18\x07 \x03(\x0b\x32\x1f.RawInstructors.Office_location\x1a\x31\n\x0fOffice_location\x12\x10\n\x08\x62uilding\x18\x01 \x01(\t\x12\x0c\n\x04room\x18\x02 \x01(\tb\x06proto3'
)




_RAWINSTRUCTORS_OFFICE_LOCATION = _descriptor.Descriptor(
  name='Office_location',
  full_name='RawInstructors.Office_location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='building', full_name='RawInstructors.Office_location.building', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='room', full_name='RawInstructors.Office_location.room', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=272,
)

_RAWINSTRUCTORS = _descriptor.Descriptor(
  name='RawInstructors',
  full_name='RawInstructors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instructor_id', full_name='RawInstructors.instructor_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='RawInstructors.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='RawInstructors.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hire_date', full_name='RawInstructors.hire_date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_active', full_name='RawInstructors.is_active', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subjects_taught', full_name='RawInstructors.subjects_taught', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='office_location', full_name='RawInstructors.office_location', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RAWINSTRUCTORS_OFFICE_LOCATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=272,
)

_RAWINSTRUCTORS_OFFICE_LOCATION.containing_type = _RAWINSTRUCTORS
_RAWINSTRUCTORS.fields_by_name['office_location'].message_type = _RAWINSTRUCTORS_OFFICE_LOCATION
DESCRIPTOR.message_types_by_name['RawInstructors'] = _RAWINSTRUCTORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RawInstructors = _reflection.GeneratedProtocolMessageType('RawInstructors', (_message.Message,), {

  'Office_location' : _reflection.GeneratedProtocolMessageType('Office_location', (_message.Message,), {
    'DESCRIPTOR' : _RAWINSTRUCTORS_OFFICE_LOCATION,
    '__module__' : 'instructors_pb2'
    # @@protoc_insertion_point(class_scope:RawInstructors.Office_location)
    })
  ,
  'DESCRIPTOR' : _RAWINSTRUCTORS,
  '__module__' : 'instructors_pb2'
  # @@protoc_insertion_point(class_scope:RawInstructors)
  })
_sym_db.RegisterMessage(RawInstructors)
_sym_db.RegisterMessage(RawInstructors.Office_location)


# @@protoc_insertion_point(module_scope)
