# mypy: ignore-errors
# isort: skip_file
# fmt: off

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instructors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11instructors.proto\"\xfa\x01\n\x0eRawInstructors\x12\x15\n\rinstructor_id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x11\n\thire_date\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x17\n\x0fsubjects_taught\x18\x06 \x03(\t\x12\x38\n\x0foffice_location\x18\x07 \x03(\x0b\x32\x1f.RawInstructors.Office_location\x1a\x31\n\x0fOffice_location\x12\x10\n\x08\x62uilding\x18\x01 \x01(\t\x12\x0c\n\x04room\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instructors_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RAWINSTRUCTORS']._serialized_start=22
  _globals['_RAWINSTRUCTORS']._serialized_end=272
  _globals['_RAWINSTRUCTORS_OFFICE_LOCATION']._serialized_start=223
  _globals['_RAWINSTRUCTORS_OFFICE_LOCATION']._serialized_end=272
# @@protoc_insertion_point(module_scope)
