# mypy: ignore-errors
# isort: skip_file
# fmt: off

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rclasses.proto\"\xf9\x02\n\nRawClasses\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\t\x12\x11\n\tcourse_id\x18\x02 \x01(\t\x12\x15\n\rinstructor_id\x18\x03 \x01(\x03\x12&\n\x08schedule\x18\x04 \x03(\x0b\x32\x14.RawClasses.Schedule\x12\x13\n\x0broom_number\x18\x05 \x01(\x03\x12\x14\n\x0cmax_capacity\x18\x06 \x01(\x03\x12&\n\x08sessions\x18\x07 \x03(\x0b\x32\x14.RawClasses.Sessions\x12\x15\n\rexam_datetime\x18\x08 \x01(\t\x1al\n\x08Schedule\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x61ys_of_week\x18\x03 \x03(\t\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\x1a/\n\x08Sessions\x12\x14\n\x0csession_date\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RAWCLASSES']._serialized_start=18
  _globals['_RAWCLASSES']._serialized_end=395
  _globals['_RAWCLASSES_SCHEDULE']._serialized_start=238
  _globals['_RAWCLASSES_SCHEDULE']._serialized_end=346
  _globals['_RAWCLASSES_SESSIONS']._serialized_start=348
  _globals['_RAWCLASSES_SESSIONS']._serialized_end=395
# @@protoc_insertion_point(module_scope)
